### PR TITLE
Upgrade to meta v2 and metaconfig v0.5

### PR DESCRIPTION
**Pull request by olafurpg**
- Remove sbt-bintray.
- Configure CI to publish to sonatype on tag push.
- Turn of npm warnings about licence, we don't publish packages to npm, yet.

### CODE REVIEW

**Comment by gabro** [comment]
🙌 nice!

**Comment by olafurpg** [comment]
First run

> ./bin/ci-publish.sh: line 18: [: missing `]'

:sob:

I got it working for the scalameta and metaconfig repo. Release on tag push is so promising :smile: and surprisingly simple to setup once you figure out the right gpg commands

**Comment by gabro** [comment]
bash is hard, you can probably dry run the script locally with the right env variables

**Comment by gabro** [comment]
maybe running it inside a docker Linux image, osx bash is a bit different

**Comment by olafurpg** [comment]
I did dry run it locally, but OSX allows single brackets. I'm planning to move this into an sbt-plugin to avoid this bash business

**Comment by olafurpg** [comment]
NB. Release on tag push will make it much simpler to stick to a release schedule. I'm very excited about this. Releasing is incredibly time consuming esp. for larger projects like scalameta that contain >60 modules when you take into account the full cross-build

**Comment by olafurpg** [comment]
https://travis-ci.org/scalacenter/scalafix/jobs/253903395#L2274
> [info] repositoryClosed: id:chepflscala-1056

It works 🎉

**Comment by gabro** [comment]
Cool! That definitely will allow releasing more often!

**Pull request merged**
