### PR TITLE
scalameta 4.6.0 (requires mdoc 2.3.6)

### PR DESCRIPTION
**Pull request by bjaglin**
- https://github.com/scalameta/scalameta/pull/2805 should fix https://github.com/scalacenter/scalafix/issues/962
- https://github.com/scalameta/scalameta/pull/2815 should just bring some deprecations to community rules like https://github.com/xuwei-k/scalafix-rules/blob/main/rules/src/main/scala/fix/Scala3Placeholder.scala
- work on Scala 3 dialects -> we might want to tweak https://github.com/scalacenter/scalafix/blob/22626c727db7a636d0e5e2cd842b278af50a9605/scalafix-core/src/main/scala/scalafix/internal/config/ScalaVersion.scala#L23

### CODE REVIEW

**Comment by bjaglin** [comment]
It looks like https://github.com/scalameta/scalameta/pull/2812 is [source-compatible](https://github.com/scalacenter/scalafix/actions/runs/3170104222/jobs/5162467860) but [not binary-compatible](https://github.com/scalacenter/scalafix/actions/runs/3170104222/jobs/5162467860) for (internal) class `scala.meta.internal.inputs.package$.XtensionInputSyntaxStructure`, so we'll need a new minor release of mdoc.

**Comment by tgodzik** [comment]
Ok, raised a PR [here](https://github.com/scalameta/mdoc/pull/710) that should remove the usage of the incompatible methods:

There is also some usage of other methods, but they are much more simple and we can work on that in the future.

**Comment by tgodzik** [comment]
I am running the new release here: https://github.com/scalameta/mdoc/actions/runs/3180679269

You should be able to bump both scalameta and mdoc.

**Comment by bjaglin** [comment]
> https://github.com/scalameta/scalameta/pull/2805 should fix https://github.com/scalacenter/scalafix/issues/962

```
➜  /tmp touch dll.dylib
➜  /tmp cs launch scalafix:0.10.3 -- --classpath=/tmp/dll.dylib 
error: Unable to load symbol table: zip file is empty
➜  /tmp cs launch -r sonatype:snapshots scalafix:0.10.3+4-ad2f5447-SNAPSHOT -- --classpath=/tmp/dll.dylib
No rules requested to run
```
:heavy_check_mark:

**Comment by bjaglin** [comment]
> https://github.com/scalameta/scalameta/pull/2815 should just bring some deprecations to community rules like https://github.com/xuwei-k/scalafix-rules/blob/main/rules/src/main/scala/fix/Scala3Placeholder.scala

```bash
➜  scalafix-rules git:(main) ✗ tail -n2 project/plugins.sbt                                                                     
resolvers += Resolver.sonatypeRepo("snapshots")
dependencyOverrides += "ch.epfl.scala" % "scalafix-interfaces" % "0.10.3+4-ad2f5447-SNAPSHOT"
➜  scalafix-rules git:(main) ✗ sbt "testsTarget3/testOnly *RuleSuite -- -z fix/Scala3PlaceholderTest.scala"
[warn] /home/brice/git/opensource/scalafix-rules/rules/src/main/scala/fix/Scala3Placeholder.scala:15:21: object Placeholder in object Type is deprecated (since >4.5.13): Placeholder replaced with AnonymousParam and Wildcard
[warn]       case t @ Type.Placeholder(Bounds(None, None)) if t.toString == "_" =>
[warn]                     ^
[warn] one warning found
[info] compiling 1 Scala source to /home/brice/git/opensource/scalafix-rules/tests/target/target3-jvm-2.12/test-classes ...
[info] RuleSuite:
[info] - fix/Scala3PlaceholderTest.scala
[info] Run completed in 926 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 19 s, completed Oct 9, 2022, 7:53:46 PM
```

:heavy_check_mark:

**Pull request merged**
