### PR TITLE
Fix #309, handle trickier symbolic identifiers.

### LINKED ISSUE #309: ExplicitReturnTypes rewrite invalid pattern in type ascription
Before

```scala
implicit val materializer_ = ActorMaterializer()
```

After

```scala
implicit val materializer_: akka.stream.ActorMaterializer = ActorMaterializer()
```

This is a syntax error.

```scala
 val foo_: Int = 1
<console>:1: error: illegal start of simple pattern
val foo_: Int = 1
              ^

scala> val foo_ : Int = 1
foo_: Int = 1
```

the `_` and the `:` must be separated by a space

### PR DESCRIPTION
**Pull request by olafurpg**

### CODE REVIEW

**Comment by dragos** [comment]
LGTM! Thanks for the very quick reaction!

**Comment by dragos** [comment]
@olafurpg how can I try the fixes? do you publish SNAPSHOTS?

**Comment by olafurpg** [comment]
I just pushed the tag to publish M7 with this fix, it usually takes ~30 minutes to run via CI and sync. publishLocal until then ;)

We don't publish SNAPSHOT, we used to publish to bintray on every merge but no longer. It should probably be quite easy to configure the CI to publish a sonatype SNAPSHOT on every merge into master, it already know how to publish non-SNAPSHOTs on tag push 😄

**Comment by olafurpg** [comment]
FYI, https://github.com/scalameta/scalameta/pull/1076 will soon make ExplicitReturnTypes more robust. Currently it randomly shortens magic names like List/StringBuilder/Long resulting in bugs like #254

**Comment by dragos** [comment]
Cool, I'll try M7. BTW, what's the status on trailing commas? It seems like it should be supported, but I see errors.

**Comment by olafurpg** [comment]
> what's the status on trailing commas?

trailing commas have been supported in the scalameta parser since february, it could be that scalafix is using the wrong dialect. Can you report an issue with reproduction?

**Pull request merged**
