### PR TITLE
Add scalafix.cli.Cli back

### LINKED ISSUE #746: Add back scalafix.cli.Cli
Recent refactorings moved it to scalafix.v1.Main in order to keep both clis, now there is only one so we can move it to the original location.

### PR DESCRIPTION
**Pull request by olafurpg**
Fixes #746 

cc/ @usrinivasan

### CODE REVIEW

**Comment by usrinivasan** [comment]
@olafurpg please publish scalafix-cli_2.11.12;0.6.0-M9

**Comment by olafurpg** [comment]
I already cut a release right after merging but Travis CI timed out during
publish. Seems Sonatype is extra slow these days, I will try again later
once I'm back at the computer.

**Comment by olafurpg** [comment]
Timed out again, publishing locally.

**Comment by olafurpg** [comment]
Weird, publishing now took only ~10-15 minutes. Artifacts should be on their way to maven central! @usrinivasan

**Comment by usrinivasan** [comment]
Thank you @olafurpg !

**Pull request merged**
