### PR TITLE
Unused pattern match

### PR DESCRIPTION
**Pull request by vincenzobaz**
This PR aims at fixing #1304 by replacing unused pattern match variables with the `_` wildcard.

This is my first contribution to the scalafix project so any advice or remark is welcome.
I am a bit concerned about test exhaustivity...

### CODE REVIEW

**Review by bjaglin — COMMENTED** [review]
Nice, thanks for the PR :+1: 

Maybe you can also update https://github.com/scalacenter/scalafix/blob/e31e5c946a14bb3839ef5c087b660953a3485db8/docs/rules/RemoveUnused.md (the bottom seems weird by the way, mentioning SCALA212 twice) ?

**Review by mlachkar — COMMENTED** [review]
LGTM. 
So for 2.11, this new config won't work. There no scalacOption to show unused pattern matchs. 
You will need to move the `input` tests under the folder 2.12 and 2.13, same for the output. 
In the documentation, we will need to mention under Scala211 that the new configuration won't have any effect. Or maybe we can add this information to the description :
```
 @Description("Remove unused pattern match variables in scala 2.12 and 2.13")
    patternvars: Boolean = true
```

**Comment by vincenzobaz** [comment]
@bjaglin thank you for the review. I do not understand what is duplicated in the page that you link.

**Comment by bjaglin** [comment]
> @bjaglin thank you for the review. I do not understand what is duplicated in the page that you link.

Apologies, I wasn't clear - I meant https://github.com/scalacenter/scalafix/blame/e31e5c946a14bb3839ef5c087b660953a3485db8/docs/rules/RemoveUnused.md#L98-L122 (it's not directly related to this PR, merely a boy scout rule suggestion!)

**Review by mlachkar — APPROVED** [review]

**Pull request merged**
