### PR TITLE
CI cleanup

### PR DESCRIPTION
**Pull request by bjaglin**
From what I see, CI is now completely handled by GH actions. Does it mean we can clean-up/close the travis/drone/appveyor accounts?

### CODE REVIEW

**Comment by bjaglin** [comment]
I just realized https://github.com/scalacenter/scalafix/blob/ddbc97ad0fbc7683ad7a6d250f5b69cf4289d7b7/.travis.yml#L15 is still to be migrated

**Comment by mlachkar** [comment]
I can migrate the doc release part.

**Comment by mlachkar** [comment]
it's weird that the formatting change that much.. Do you have any clue on that ?

**Comment by bjaglin** [comment]
@mlachkar there were a lot of changes in the recent minor scalafmt versions, so I am not very surprised. https://github.com/scalacenter/scalafix/pull/1136/files?w=1 removes some noise

**Comment by mlachkar** [comment]
sbt docs/docusaurusPublishGhpages has been migrated to GH

**Comment by bjaglin** [comment]
@mlachkar thanks, I have rebased this and spined off the scalafmt bump to https://github.com/scalacenter/scalafix/pull/1274

**Review by mlachkar — APPROVED** [review]

**Pull request merged**
