### PR TITLE
Upgrade to Scala 2.13.4

### PR DESCRIPTION
**Pull request by mlachkar**
Similar to https://github.com/scalacenter/scalafix/pull/1179

### CODE REVIEW

**Comment by mlachkar** [comment]
@bjaglin I need help on the mima ci issue. I don't understand why it's still try to download `/semanticdb-scalac-core_2.13.4/4.3.24`. 

Thanks

**Comment by bjaglin** [comment]
> @bjaglin I need help on the mima ci issue. I don't understand why it's still try to download `/semanticdb-scalac-core_2.13.4/4.3.24`.
> 
> Thanks

@mlachkar you need to update https://github.com/scalacenter/scalafix/blob/4c2eb94b9bf5cda08263cfca42466f0c881a29fc/project/ScalafixBuild.scala#L271

**Comment by mlachkar** [comment]
I think I don't fully understand the` PreviousScalaVersion Map`. It could be empty, it would give the same result.

**Comment by bjaglin** [comment]
> I think I don't fully understand the` PreviousScalaVersion Map`. It could be empty, it would give the same result.

Indeed, my suggestion didn't make sense. I'll have a look at that today.

**Comment by bjaglin** [comment]
It looks like a regression in MiMa introduced in https://github.com/lightbend/mima/pull/508 - see last commit details. I'll follow up there, for the time being I think it's easier to downgrade.

**Comment by mlachkar** [comment]
If it's ok for you, we can merge and then release ?

**Comment by bjaglin** [comment]
> If it's ok for you, we can merge and then release ?

sure of course!

**Comment by daddykotex** [comment]
Thanks for the hard work 👍

**Pull request merged**
