### PR TITLE
Add documentation to cross publish rules

### PR DESCRIPTION
**Pull request by mlachkar**

### CODE REVIEW

**Review by bjaglin — COMMENTED** [review]
I am wondering if this couldn't be merged into an existing section, just before https://github.com/scalacenter/scalafix/blob/55de64204b6e326034528b85ac64729d62515168/docs/developers/tutorial.md#publish-the-rule-to-maven-central? We should also move https://github.com/olafurpg/named-literal-arguments/commits/master to the scalacenter organization and cross-publish that one.

**Review by olafurpg — APPROVED** [review]
LGTM 👍

**Comment by mlachkar** [comment]
I added a link in the tutorial for developers to read the cross-publish page once they have set up the configuration/ whatever necessary, to push to Maven central. Is that ok for @bjaglin  ?

**Review by bjaglin — APPROVED** [review]
thanks!

**Pull request merged**
