### PR TITLE
Upgrade to Scala 2.13.4

### PR DESCRIPTION
**Pull request by daddykotex**
Similar to https://github.com/scalacenter/scalafix/pull/1179

### CODE REVIEW

**Comment by daddykotex** [comment]
We use sbt-scalafix and the `scalafixSemanticdb` sbt key which seems to depend on this.

**Comment by daddykotex** [comment]
I'm clearly missing a piece of the puzzle here. 

`sbt-scalafix` defines the relevant keys like:

```scala
val scalafixSemanticdb: ModuleID =
      scalafixSemanticdb(BuildInfo.scalametaVersion)
def scalafixSemanticdb(scalametaVersion: String): ModuleID =
      "org.scalameta" % "semanticdb-scalac" % scalametaVersion cross CrossVersion.full
```

BuildInfo.scala defines `scalametaVersion` like `def scalametaVersion: String = property("scalametaVersion")` and in this case, `property` loads a properties files called: `scalafix-interfaces.properties` that seems to be coming from: `https://github.com/scalacenter/scalafix/tree/master/scalafix-interfaces` (back in this repo)

**Comment by daddykotex** [comment]
if I add this diff:

```diff
diff --git a/build.sbt b/build.sbt
index 0a88d5f3..24f00d74 100644
--- a/build.sbt
+++ b/build.sbt
@@ -6,7 +6,7 @@ inThisBuild(
     crossScalaVersions := List(scala213, scala212, scala211),
     fork := true,
     semanticdbEnabled := true,
-    semanticdbVersion := scalafixSemanticdb.revision,
+    semanticdbVersion := "4.4.0",
     scalacOptions ++= List("-P:semanticdb:synthetics:on"),
     scalafixScalaBinaryVersion := scalaBinaryVersion.value,
     scalafixDependencies += "com.github.liancheng" %% "organize-imports" % "0.4.3"
```

it works fine, so I guess `sbt-scalafix` has to be updated beforehand.

**Comment by daddykotex** [comment]
That would be a dependency cycle:

1.  the CI on this build needs sbt-scalafix `scalafixSemanticdb` to be updated
2. `scalafixSemanticdb` depends on a property file generated in this build, in the `interfaces` module

**Comment by mlachkar** [comment]
You are right, there is a dependency cycle, butThe Scalafix plugin can be disabled until we finish this upgrade (or we fix manually the version of semanticdb for the plugin.)

**Comment by mlachkar** [comment]
I wanted to push on top of this commit, but by mistake I opened a new PR https://github.com/scalacenter/scalafix/pull/1291

**Comment by daddykotex** [comment]
No problem, thanks @mlachkar

**Pull request closed without merging**
