### PR TITLE
Fix RemoveUnusedPatternVars

### LINKED ISSUE #604: ignore generated (expanded macros) code
#559

### LINKED ISSUE #1343: Remove unused doesn't remove unused pattern vars when inside a method
To reproduce the issue:
```
  def test(): Unit = {
    example match {
      case AB(a, b) => println("Not used, wrong")
    }
  }
```
The regex used to catch the diagnostic message is too specific to values

### PR DESCRIPTION
**Pull request by vincenzobaz**
This PR aims at fixing #1343 by using a more general regexp and adding several tests.

closes #1343

### CODE REVIEW

**Review by mlachkar — APPROVED** [review]

**Comment by mlachkar** [comment]
@vincenzobaz can you check why the tests are failing .. I find that strange the renameSuite is failing. Can you also run bin/scalafmt. Thanks

**Comment by mlachkar** [comment]
I am having issues understanding the issue with this PR. The change should not affect the other tests, but it's the case. 
When debugging, the list of diagnostics is empty in the failing tests. 
In my tests, the semanticdb files were produce during compilation time, not by interactive.global. 
I am quite blocked by this bug. @bjaglin what do you think we should do ?

**Comment by mlachkar** [comment]
same code, but the tests are passing https://github.com/scalacenter/scalafix/pull/1355

**Comment by mlachkar** [comment]
So after further debugging: in fact when adding these new case tests, we don't have warnings anymore on some files...

**Comment by mlachkar** [comment]
I have just removed a number of tests that were added by this pull request.
Something in those tests was making the compiler not producing anymore "unused warning" for other files.

**Comment by bjaglin** [comment]
>  Something in those tests was making the compiler not producing anymore "unused warning" for other files.

Could it be a limit in the compiler output? https://docs.scala-lang.org/overviews/compiler-options/index.html
>  -Xmaxwarns ARG
>
>   Maximum warnings to print
>   Default: 100

**Comment by mlachkar** [comment]
I think it should be that! completly forgot about this :s

**Comment by mlachkar** [comment]
It also means that this rule fixes maximum 100 warns by default ^^

**Comment by bjaglin** [comment]
> It also means that this rule fixes maximum 100 warns by default (in each run)^^

https://github.com/scalacenter/scalafix/issues/1264

We could mention it in the docs at least?

**Pull request merged**
