### PR TITLE
ensure scalacOptions are honored in 2.13

### PR DESCRIPTION
**Pull request by bjaglin**
Follows https://github.com/scalacenter/scalafix/pull/1215
Confirms that https://github.com/scalameta/scalameta/pull/2216 is fixed

### CODE REVIEW

**Comment by mlachkar** [comment]
That's really nice!

**Review by mlachkar — APPROVED** [review]

**Comment by bjaglin** [comment]
> That's really nice!

I ran into the scalameta issue for something else and it reminded me your PR!

I was looking for a ticket to close (https://github.com/scalacenter/scalafix/pull/1215#discussion_r528829077), but I guess we didn't have any?

**Comment by mlachkar** [comment]
We had one https://github.com/scalameta/scalameta/pull/2094, and they closed it, but I thought it was just because they were enabled to reproduce the issue.

**Comment by tgodzik** [comment]
> We had one [scalameta/scalameta#2094](https://github.com/scalameta/scalameta/pull/2094), and they closed it, but I thought it was just because they were enabled to reproduce the issue.

I managed to reproduce it and it should be fixed. Are you having still issues? The test from your PR is currently being run on all supported versions.

**Comment by bjaglin** [comment]
> Are you having still issues? The test from your PR is currently being run on all supported versions.

That PR shows that it's fixed upstream indeed, thanks!

What I meant is that I thought we had a ticket here to track the fact that we wanted to remove the scala 2.13 exception https://github.com/scalacenter/scalafix/pull/1215#discussion_r528829077, but it looks like no ticket was created.

**Pull request merged**
