### PR TITLE
Don't generate semanticdb files if there are missing 

### PR DESCRIPTION
**Pull request by mlachkar**
- instead we report an error of semanticdb files missing

### CODE REVIEW

**Comment by tgodzik** [comment]
In this case, would it be possible to be able to provide semanticdb via `Array[Byte]` in the API? Not neccessarily in this PR and I know we discussed it previously, but this would be amazing to have as it would enable us to make it work in a bunch of places.

**Comment by mlachkar** [comment]
We need to think and design this solution. Metals uses scalafix to fix only one file, by the api takes multiple files and in this case how do we differentiate between semanticdb files.
Maybe we need a new api that fixes only one file and in this case we can provide the semantic file.

**Comment by tgodzik** [comment]
> We need to think and design this solution. Metals uses scalafix to fix only one file, by the api takes multiple files and in this case how do we differentiate between semanticdb files.
> Maybe we need a new api that fixes only one file and in this case we can provide the semantic file.

Maybe we could have an additional Map[String, Array[Byte] ? Or Path instead of string, I am not sure exactly what is currently used :sweat_smile:

**Review by bjaglin — APPROVED** [review]
Limiting the usage of the compiler to advanced semantic rules (for the presentation compiler) and for scalafix-reflect to compile source rule is probably a step in the right direction.

As already discussed in https://github.com/scalacenter/scalafix/pull/1348#pullrequestreview-604155677, this ondemand, transparent compilation causes a lot of confusion when the compiler kicks in in 2.12 (default loaded by most clients) against 2.13 classfiles (we had a few gitter questions / github tickets about that), so it's doing more harm than good in my opinion. When it works, it's so silent that the user might not realize there is something wrong with its semanticdb setup and could end up blaming scalafix for the very long run time.

**Comment by bjaglin** [comment]
> > We need to think and design this solution. Metals uses scalafix to fix only one file, by the api takes multiple files and in this case how do we differentiate between semanticdb files.
> > Maybe we need a new api that fixes only one file and in this case we can provide the semantic file.
> 
> Maybe we could have an additional Map[String, Array[Byte] ? Or Path instead of string, I am not sure exactly what is currently used sweat_smile

Makes sense, maybe let's follow up on https://github.com/scalacenter/scalafix/issues/1236 for this?

**Pull request merged**
