### PR TITLE
Add new Scalafix logo

### PR DESCRIPTION
**Pull request by bishabosha**
tweaked from #1574 to make the gear the same stroke size as the surrounding hexagon (70px)

### CODE REVIEW

**Comment by bishabosha** [comment]
alternative to try that is less similar to scaladex:

scalafix-logo2-demo

**Comment by bishabosha** [comment]
same but with thicker cog
scalafix-logo3-demo3

**Comment by mlachkar** [comment]
last one is my favourite

**Comment by bishabosha** [comment]
I've pushed again with the logo of https://github.com/scalacenter/scalafix/pull/1575#issuecomment-1077860070

**Review by mlachkar — APPROVED** [review]

**Comment by SethTisue** [comment]
awesome

**Comment by SethTisue** [comment]
Stickers! THE MASSES DEMAND STICKERS!

**Pull request merged**
