### PR TITLE
Support `LambdaType` and `MatchType`

### LINKED ISSUE #1766: `MatchError` on `LambdaType` in scala 3.3.1-RC1
After upgrading to scala 3.3.1-RC1 I've started seeing a `MatchError` in a number of files. One example looks like this:

```
scalafix.internal.v1.FileException: unexpected error processing file /path/to/my/file.scala
Caused by: scala.MatchError: LambdaType(Some(Scope(Vector(),Vector(SymbolInformation([B],SCALA,TYPE_PARAMETER,0,B,TypeSignature(None,TypeRef(Empty,scala/Nothing#,Vector()),TypeRef(Empty,scala/Any#,Vector())),Vector(),Empty,Vector(),None)))),TypeRef(SingleType(Empty,cats/data/NonEmptyMapImpl.),cats/data/Newtype2#Type#,Vector(TypeRef(Empty,scala/Int#,Vector()), TypeRef(Empty,[B],Vector())))) (of class scala.meta.internal.semanticdb.LambdaType)
  at scalafix.internal.v0.LegacyCodePrinter.pprint(LegacyCodePrinter.scala:103)
  at scalafix.internal.v0.LegacyCodePrinter.$anonfun$loop$4(LegacyCodePrinter.scala:204)
  at scalafix.internal.v0.LegacyCodePrinter.$anonfun$loop$4$adapted(LegacyCodePrinter.scala:204)
  at scalafix.internal.v0.LegacyCodePrinter.$anonfun$mkString$1(LegacyCodePrinter.scala:49)
  at scalafix.internal.v0.LegacyCodePrinter.$anonfun$mkString$1$adapted(LegacyCodePrinter.scala:43)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.IterableLike.foreach(IterableLike.scala:74)
  at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
  at scalafix.internal.v0.LegacyCodePrinter.mkString(LegacyCodePrinter.scala:43)
  at scalafix.internal.v0.LegacyCodePrinter.loop(LegacyCodePrinter.scala:204)
  at scalafix.internal.v0.LegacyCodePrinter.loop(LegacyCodePrinter.scala:181)
  at scalafix.internal.v0.LegacyCodePrinter.convertSynthetic(LegacyCodePrinter.scala:209)
  at scalafix.internal.v0.LegacySemanticdbIndex$.syntheticToLegacy(LegacySemanticdbIndex.scala:171)
  at scalafix.internal.v0.LegacySemanticdbIndex.$anonfun$synthetics$1(LegacySemanticdbIndex.scala:53)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.IterableLike.foreach(IterableLike.scala:74)
  at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
  at scala.collection.TraversableLike.map(TraversableLike.scala:286)
  at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
  at scalafix.internal.v0.LegacySemanticdbIndex.synthetics(LegacySemanticdbIndex.scala:52)
  at scalafix.internal.scaluzzi.Disable.checkSynthetics(Disable.scala:163)
  at scalafix.internal.scaluzzi.Disable.check(Disable.scala:184)
  at scalafix.internal.v0.LegacyRule$.lints(LegacyRule.scala:12)
  at scalafix.internal.v0.LegacySemanticRule.fix(LegacySemanticRule.scala:29)
  at scalafix.internal.v1.Rules.$anonfun$semanticPatch$1(Rules.scala:78)
  at scala.collection.immutable.List.map(List.scala:293)
  at scalafix.internal.v1.Rules.semanticPatch(Rules.scala:76)
  at scalafix.internal.v1.MainOps$.getPatchesAndDiags(MainOps.scala:305)
  at scalafix.internal.v1.MainOps$.unsafeHandleFile(MainOps.scala:255)
```

### PR DESCRIPTION
**Pull request by mrdziuban**
Fixes #1766 

@bjaglin I still haven't been able to reproduce the error through the test inputs and I'm not sure how to test this otherwise. It compiles, but I have no idea if it prints the correct thing for each type.

### CODE REVIEW

**Comment by bjaglin** [comment]
Thanks for putting this together!

Sorry for not following-up on https://github.com/scalacenter/scalafix/issues/1766#issuecomment-1591989056. Taking a deeper look at the [stack trace](https://github.com/scalacenter/scalafix/issues/1766#issue-1734304708), it looks like I was too fast suggesting a testkit test (apologies), as it's actually only a specific Scalafix API that is affected:
```
  at scalafix.internal.v0.LegacySemanticdbIndex.synthetics(LegacySemanticdbIndex.scala:52)
```

So we need an integration test, probably based on `BaseSemanticSuite`. The problem is that it's still coupled to Scala 2 at the moment (while these [2 new types are only expressable in Scala 3](https://github.com/scalameta/scalameta/issues/2403)), so you won't be able to craft them.

https://github.com/scalacenter/scalafix/blob/0cf7bd7570292a6806d6da3e3f372b20ccad8223/scalafix-tests/integration/src/test/scala/scalafix/tests/core/BaseSemanticSuite.scala#L19

So there is a bit of testing infrastructure refactoring to be done in order to test /see the effect of this properly. I don't really have an idea how to do it at the moment, I will most likely get to it in the coming weeks.

So I'd rather put this on hold for now. In the meantime, happy to review your proposal if you have some time to explore how the `BaseSemanticSuite` hierarchy can be refactored to allow scala 3 tests in a decent way.

**Comment by bjaglin** [comment]
I pushed to this branch to patch other places missing support, hoping I could rush the whole thing for Scalafix 0.11.1, but I am not confident at all about them: the few `BaseSemanticSuite` tests I managed to get running locally still don't exercise the new code, so I will need to take a deeper look in the coming days.

**Comment by mrdziuban** [comment]
@bjaglin have you had a chance to revisit this? Not being able to run scalafix on scala 3.3.1 is one of the last things holding me back from dropping scala 2 in my project so I'm eager to get it resolved 🙂 let me know if there's anything I can do to help!

**Comment by tanishiking** [comment]
I would take a look this when I have time (hopefully within this year 🤞 ) since I introduced the upstream changes (`LambdaType` to semanticdb + Scala3).

**Comment by mrdziuban** [comment]
Hi @bjaglin and @tanishiking, do you have any update on when this might be resolved? Let me know if I can help, it's pretty much the only thing stopping me from committing fully to Scala 3

**Comment by bjaglin** [comment]
@mrdziuban sorry for the silence. I will tackle it this Friday, most likely in time for the upcoming release next week (pending Scala 2.x patch releases)

**Comment by bjaglin** [comment]
@mrdziuban I have spent hours trying to create source code that results in a LambdaType referenced in synthetics (which seems to be your scenario looking at your stack trace), but I did not manage. The current (v1) API is now fixed/tested in this PR, but I can only guess that the [deprecated (v0) one exercised by Scaluzzi](https://github.com/vovapolu/scaluzzi/pull/23) is as well.

Any chance you could minimize your problem so we can be sure the fix is right?

**Comment by mrdziuban** [comment]
@bjaglin thank you for looking! Definitely, I was able to minimize it here: https://github.com/mrdziuban/scalafix-issue-1801

**Comment by bjaglin** [comment]
@mrdziuban Great! I'll integrate as a test tonight

**Comment by bjaglin** [comment]
Thanks again for the PR @mrdziuban! The test I added in the last commit confirmed the first commit of yours was enough for your use-case. My other commits handle other code paths that you would have most likely ran into sooner or later.

**Pull request merged**
