### PR TITLE
Fix RemoveUnusedTerms for private defs

### PR DESCRIPTION
**Pull request by joan38**
Attempt to fix https://github.com/scalacenter/scalafix/issues/626

### CODE REVIEW

**Comment by joan38** [comment]
Sure will do that this evening

**Comment by olafurpg** [comment]
Thanks for this contribution @joan38 ! I am busy organizing a spree today, will try to take a closer look later this week.

**Comment by joan38** [comment]
No worries @olafurpg I know you are usually very quick ;)

@gabro I've added some tests.

**Comment by gabro** [comment]
@joan38 thanks! They seem to be failing though, can you take a look?

**Comment by joan38** [comment]
Super weird indeed the regex doesn't match on messages like:
```
private method f in object RemoveUnusedTerms is never used
```

**Comment by joan38** [comment]
I don't seem to be able to get the message for the `private val` from `index.messages`.
All though it works fine for the `private def`s.
Do you have any idea what's going on here? Is it a SementicDB issue?

**Comment by gabro** [comment]
Is the message there? Can you print `index.messages` and see how it looks like?

**Comment by joan38** [comment]
I've tried to:
```
index.messages.collect {
  case m @ Message(pos, _, UnusedPrivateLocalVal(_*)) =>
    println("m: " + m)
    pos
}.toSet
```
and then ctrl+f `private val ff` in there but can't find it.

**Comment by joan38** [comment]
@olafurpg Any idea on the `index.messages` not reporting the warning for private vals?

**Comment by olafurpg** [comment]
I am able to reproduce that the message for the private val is not included in the SemanticDB
```
➜  target git:(v1) cat unused.scala
object a {
  private val unused = 1
  private def unusedDef = 1
  def app() = println(1)
}
➜  target git:(v1) metac -Ywarn-unused:privates unused.scala
     unused.scala:2: warning: private val unused in object a is never used
  private val unused = 1
              ^
unused.scala:3: warning: private method unusedDef in object a is never used
  private def unusedDef = 1
              ^
two warnings found
➜  target git:(v1) metap META-INF/semanticdb/unused.scala.semanticdb
unused.scala
------------

...
Diagnostics:
[2:2..2:27)[warning] private method unusedDef in object a is never used
```

It could be that the message is reported in a later compile phase. I recommend we limit this PR to unused defs and follow up with a ticket in scalameta/scalameta :)

**Comment by joan38** [comment]
Done. Only private vals are missing. I left the regex modification for later when the semantic DB will be fixed.

**Comment by joan38** [comment]
@olafurpg @gabro Ready to go with this?

**Comment by joan38** [comment]
Cheers @olafurpg

**Pull request merged**
