### PR TITLE
Fine-tune github: protocol.

### PR DESCRIPTION
**Pull request by olafurpg**
I hadn't actually tried it yet, whoops. This expansion should match the
boilerplate created by g8 scalacenter/scalafix.g8

### CODE REVIEW

**Comment by gabro** [comment]
mm, how can I test this?

I'm trying:

```sh
sbt new scalacenter/scalafix.g8 --rewrite "reponame" --version=v1.0
```

but I get 

```
Template not found for:
```

**Comment by olafurpg** [comment]
Good catch @gabro !  The assignment `=` character is apparently necessary

```
sbt new scalacenter/scalafix.g8 --rewrite="reponame" --version=v1.0
```

I updated the docs and also improved the error message when the user mistypes the `github:` protocol

**Comment by gabro** [comment]
image


mm what am I getting wrong? 🤔

**Comment by olafurpg** [comment]
Are you using the latest sbt version? I'm on 0.13.15

**Comment by gabro** [comment]
Same...
Do I need to do anything specific to pull the template in?

The odd thing is that it doesn't even say which template it can't find.

**Comment by gabro** [comment]
Oh, apparently it worked in interactive mode. Something fishy going on with zsh...

**Comment by gabro** [comment]
For the record 

```sh
sbt "new scalacenter/scalafix.g8 --rewrite=fix --version=v1.0"
```

works as expected instead. Apparently without the quotes the arguments are not passed down to `sbt new`.

**Pull request merged**
