### PR TITLE
Cross-compile core to Scala.js

### PR DESCRIPTION
**Pull request by gabro**
Very WIP.

This PR serves a base for a discussion :)

Blocking things I've noticed so far:
- `metaconfig-typesafe-config` seems to be missing from maven
- `googleDiff` is the only JVM-only dependency. We can probably extract the diffing part into a separate module that uses `googleDiff` for the JVM and some other diffing library for JS.

Minor:
- The strategy of putting deps in `Dependencies.scala` falls short for cross deps (I've just inlined them for now)
- I couldn't find an easy way of making `.configure(setId)` work for `CrossProject`. I've just manually configured the cross project for now

### CODE REVIEW

**Comment by gabro** [comment]
This looks like a valid candidate for the JS implementation of diff.

https://github.com/kpdecker/jsdiff

**Comment by gabro** [comment]
I just realized I've no idea of how to implement the same interface differently for JS and JVM in a cross build. Is this even possible?

Ideally for the JVM project we'd use `googleDiff` and for the JS one `jsdiff`.

**Comment by gabro** [comment]
Ok, I figured that one out (people were nice on gitter :D). I've just pushed a tentative `scalafix-diff` module that abstracts over the diff generation cross platform.

If you're ok with this approach @olafurpg I'll add some tests to ensure consistent outputs across the two platforms.

**Comment by olafurpg** [comment]
@gabro This is awesome! 

To quickly answer your questions
- `metaconfig-hocon` can be used on JS, http://search.maven.org/#artifactdetails%7Ccom.geirsson%7Cmetaconfig-hocon_sjs0.6_2.12%7C0.4.0%7Cjar That's what scalafmt does https://github.com/scalameta/scalafmt/blob/d204ae1437247aae0f0b8a9901e433368057e678/build.sbt#L41-L46 metaconfig-hocon is not as robust as the typesafe config variant, but we can always fix that if it becomes an issue.
- The `Patch.diff` method can be moved to `scalafix.util.Diff(Input, Input)` with the current implementation the `jvm/` directory with a dummy implementation in core. No need for a separate project.

I would like to get the fix for #224 in before we do this change, since I have a fairly large pending diff. Will review closer after that fix is ready ;)

**Comment by olafurpg** [comment]
As for the tests, we should be able to run most of the SemanticTests under JS. It's fine to move them all to jvm only to begin with, but only the ones that do classloading or runtime compilation need to be on the jvm. The io module works on Node.js and semantic api work in JS too.

**Comment by olafurpg** [comment]
#228 is the PR I'd like to merge first to avoid rebase issues.

**Comment by olafurpg** [comment]
Heads up, I'm rebasing this PR on top of master and fixing the resolution errors.

**Pull request closed without merging**
