### PR TITLE
Test against JDK20

### PR DESCRIPTION
**Pull request by bjaglin**

### CODE REVIEW

**Comment by bjaglin** [comment]
```
 - PrettyTest.scala *** FAILED *** (792 milliseconds)
  java.lang.IllegalArgumentException: Unsupported class file major version 64
  at scala.tools.asm.ClassReader.<init>(ClassReader.java:199)
  at scala.tools.asm.ClassReader.<init>(ClassReader.java:180)
  at scala.tools.asm.ClassReader.<init>(ClassReader.java:166)
  at scala.tools.asm.ClassReader.<init>(ClassReader.java:287)
  at scala.meta.internal.metacp.package$.scala$meta$internal$metacp$package$$readInputStreamToClassNode(package.scala:89)
  at scala.meta.internal.metacp.package$XtensionAsmClassfileOps$.hasScalaSig$extension(package.scala:78)
  at scala.meta.internal.scalacp.SymbolIndex.$anonfun$lookup$1(SymbolIndex.scala:30)
  at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:454)
  at scala.meta.internal.scalacp.SymbolIndex.lookup(SymbolIndex.scala:13)
  at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSpec.descriptor(SymbolOps.scala:115)
```

**Comment by bjaglin** [comment]
This shows that JDK20 should work fine, as the only failures seem to be related to the test runner rather than the SUT, only with the unpublished scala 3 artifacts anyway. These false positives will be fixed by the next release of scalameta which will bring a JDK20-compatible scalap, so I don't think it's worth hacking the build to force an eviction of `org.scala-lang` artifacts.

**Comment by SethTisue** [comment]
in the Scala 2.13 community build, I'm seeing a test failure on JDK 21 (after upgrading to sbt 1.9.0, since earlier versions don't work on JDK 21): https://scala-ci.typesafe.com/job/scala-2.13.x-jdk21-integrate-community-build/44/artifact/logs/scalafix-build.log

the failure reproduces for me locally as well:

```
[info] SymbolInformationSuite:
[info] - java/lang/System#lineSeparator(). *** FAILED *** (51 milliseconds)
[info]   java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "$this" is null
[info]   at scala.collection.StringOps$.head$extension(StringOps.scala:1124)
[info]   at scala.meta.internal.semanticdb.Scala$Names$.encode(Scala.scala:181)
[info]   at scala.meta.internal.semanticdb.Scala$Descriptor.toString(Scala.scala:147)
[info]   at scala.meta.internal.semanticdb.Scala$Descriptor.toString$(Scala.scala:140)
[info]   at scala.meta.internal.semanticdb.Scala$Descriptor$Parameter.toString(Scala.scala:158)
[info]   at scala.meta.internal.semanticdb.Scala$Symbols$.Global(Scala.scala:14)
[info]   at scala.meta.internal.javacp.Javacp$.$anonfun$sinfos$13(Javacp.scala:175)
[info]   at scala.collection.immutable.List.map(List.scala:246)
[info]   at scala.meta.internal.javacp.Javacp$.$anonfun$sinfos$9(Javacp.scala:169)
[info]   at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
[info]   ...
```

**Comment by SethTisue** [comment]
oh, and `integration2_13/test` fails with the same error in `PrettyExpectSuite`

**Comment by bjaglin** [comment]
I'll follow up on JDK21 compatibility in https://github.com/scalacenter/scalafix/pull/1810

**Pull request merged**
